//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Categoryld { get; set; }
        public string Price { get; set; }
        public string PublishDate { get; set; }
        public string Status { get; set; }
        public string DefaultImageId { get; set; }
        public string Quantity { get; set; }
    }
}
